// Generated by Wrangler on Wed Aug 14 2024 16:29:18 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
	AuthorizeNetApiTransactionKey: string;
	AuthorizeNetApiLoginId: string;
	AuthorizeNetApiUrl: string;
	ZoomApiBaseUrl: string;
	ZoomApiAccountId: string;
	ZoomApiClientId: string;
	ZoomApiClientSecret: string;
}
